import Head from 'next/head';
import Link from 'next/link';
import { useTheme } from 'next-themes';

import Header from '../components/Header';

export default function Home() {
  const { resolvedTheme } = useTheme();
  return (
    <>
      <Head>
        <title>Dashingly.xyz</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <div className={
          resolvedTheme === 'light' ?
            'min-h-screen flex flex-col align-middle items-center justify-between mx-auto text-center p-8 text-slate-700'
            : 'min-h-screen flex flex-col align-middle items-center justify-between mx-auto text-center p-8 bg-slate-800'
        }
        >
          <Header />
          <div>
            <p className='md:text-3xl pb-2'>Robust Data Synchronicity.</p>
            <p className='md:text-8xl pb-8 font-medium'>
              <span className='
              pr-2
              block 
              sm:inline 
              text-transparent 
              bg-clip-text 
              bg-gradient-to-br from-emerald-200 via-teal-400 to-fuchsia-500
              hover:text-transparent 
              hover:bg-gradient-to-bl from-emerald-200 via-teal-400 to-fuchsia-500
              '>
                Dashingly
              </span>
              Elegant.
            </p>
            <Link href='/dashboard'>
              <button>
                <a href="#_" class="relative inline-flex items-center justify-center px-12 py-8 overflow-hidden font-bold rounded-3xl shadow-2xl group">
                  <span class={
                    resolvedTheme === 'light' ?
                      "absolute inset-0 w-full h-full transition duration-300 ease-out opacity-0 bg-gradient-to-br from-fuchsia-500 via-cyan-300 to-emerald-200 group-hover:opacity-100"
                      : "absolute inset-0 w-full h-full transition duration-300 ease-out opacity-0 bg-gradient-to-br from-fuchsia-600 via-purple-700 to-blue-400 group-hover:opacity-100"
                  }
                  >
                  </span>
                  {/* <!-- Top glass gradient --> */}
                  <span class="absolute top-0 left-0 w-full bg-gradient-to-b from-white to-transparent opacity-5 h-1/3"></span>
                  {/* <!-- Bottom gradient --> */}
                  <span class="absolute bottom-0 left-0 w-full h-1/3 bg-gradient-to-t from-white to-transparent opacity-5"></span>
                  {/* <!-- Left gradient --> */}
                  <span class="absolute bottom-0 left-0 w-4 h-full bg-gradient-to-r from-white to-transparent opacity-5"></span>
                  {/* <!-- Right gradient --> */}
                  <span class="absolute bottom-0 right-0 w-4 h-full bg-gradient-to-l from-white to-transparent opacity-5"></span>
                  <span class="absolute inset-0 w-full h-full border border-white rounded-3xl opacity-10"></span>
                  <span class="absolute w-0 h-0 transition-all duration-300 ease-out bg-white rounded-full group-hover:w-56 group-hover:h-56 opacity-5"></span>
                  <span class="relative">See Dashboard</span>
                </a>
              </button>
            </Link>
          </div>

          <div className='flex flex-row justify-center gap-2'>
            <h4 className='text-xs sm:text-sm'>Built with 💛 by</h4>
            <button className='text-xs sm:text-sm'>
              <a href="https://jasonmai.dev" target='_blank'>
                JasonMai.dev
              </a>
            </button>
          </div>

        </div >
      </main >
    </>
  );
}
